\set ON_ERROR_STOP on

\connect config_db

CREATE TABLE public.symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(30) NOT NULL,
    exchange VARCHAR(20) NOT NULL DEFAULT 'binance',
    is_active BOOLEAN NOT NULL DEFAULT true,
    volatility_threshold NUMERIC(4, 3) NOT NULL DEFAULT 0.100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_symbols_symbol_exchange UNIQUE (symbol, exchange),
    CONSTRAINT ck_symbols_volatility_threshold CHECK (
        volatility_threshold > 0 AND volatility_threshold <= 1
    )
);

CREATE INDEX ix_symbols_active
    ON public.symbols (exchange, symbol)
    WHERE is_active;

COMMENT ON TABLE public.symbols IS
    'v2 collector universe; initialization intentionally inserts no symbols.';
COMMENT ON COLUMN public.symbols.volatility_threshold IS
    'Maximum accepted fractional price change for dirty-data filtering.';

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO config_reader;
GRANT SELECT ON TABLE public.symbols TO config_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO config_reader;
