"""Expose the TA-Lib-backed candlestick pattern registry and output contract."""

from .outputs import (
    BEARISH,
    BOUNDARY_STRENGTH,
    BULLISH,
    DIRECTIONLESS,
    FULL_STRENGTH,
    MATCHED,
    NAME_PREFIX,
    NOT_MATCHED,
    assert_pattern_name,
    match_outputs,
    no_match_outputs,
    output_keys,
    undetermined_outputs,
)
from .registry import (
    PatternRegistry,
    PatternSeries,
    PatternSpec,
    PatternState,
    PatternValue,
)
from .specs import (
    TALIB_FUNCTIONS,
    TALIB_PATTERN_REGISTRY,
    TALIB_PATTERN_REGISTRY_VERSION,
    build_talib_pattern_registry,
)
from .talib_raw import (
    TALIB_CDL_PATTERN_COUNT,
    TALIB_DBL_MAX,
    TALIB_DEFAULT_PENETRATION_SENTINEL,
    TALIB_PENETRATION_DEFAULTS,
    TALIB_RAW_ALLOWED_VALUES,
    TALIB_RAW_BOUNDARY_MAGNITUDE,
    TALIB_RAW_CONFIRMATION_MAGNITUDE,
    TALIB_RAW_MATCH_MAGNITUDE,
    TALIB_RAW_ZERO,
    TALIB_SOURCE_VERSION,
    TALIB_UNDERLYING_VERSION_PREFIX,
    TalibPatternPort,
    TalibPatternState,
    TalibRawPatternSpec,
    outputs_from_talib_integer,
    resolve_talib_penetration,
    sparse_talib_integer_signals,
    talib_integer_from_outputs,
    talib_penetration_default,
    talib_penetration_lookback,
    validate_talib_adapter_outputs,
    validate_talib_raw_integer_series,
    validate_talib_version_pin,
)

DEFAULT_PATTERN_REGISTRY = TALIB_PATTERN_REGISTRY
"""The runtime default candlestick pattern registry, backed by TA-Lib v0.7.1 ports."""

build_default_pattern_registry = build_talib_pattern_registry
"""Build the runtime default TA-Lib-backed pattern registry."""

__all__ = [
    "BEARISH",
    "BOUNDARY_STRENGTH",
    "BULLISH",
    "DEFAULT_PATTERN_REGISTRY",
    "DIRECTIONLESS",
    "FULL_STRENGTH",
    "MATCHED",
    "NAME_PREFIX",
    "NOT_MATCHED",
    "TALIB_CDL_PATTERN_COUNT",
    "TALIB_DBL_MAX",
    "TALIB_DEFAULT_PENETRATION_SENTINEL",
    "TALIB_FUNCTIONS",
    "TALIB_PENETRATION_DEFAULTS",
    "TALIB_PATTERN_REGISTRY",
    "TALIB_PATTERN_REGISTRY_VERSION",
    "TALIB_RAW_ALLOWED_VALUES",
    "TALIB_RAW_BOUNDARY_MAGNITUDE",
    "TALIB_RAW_CONFIRMATION_MAGNITUDE",
    "TALIB_RAW_MATCH_MAGNITUDE",
    "TALIB_RAW_ZERO",
    "TALIB_SOURCE_VERSION",
    "TALIB_UNDERLYING_VERSION_PREFIX",
    "PatternRegistry",
    "PatternSeries",
    "PatternSpec",
    "PatternState",
    "PatternValue",
    "TalibPatternPort",
    "TalibPatternState",
    "TalibRawPatternSpec",
    "assert_pattern_name",
    "build_default_pattern_registry",
    "build_talib_pattern_registry",
    "match_outputs",
    "no_match_outputs",
    "output_keys",
    "outputs_from_talib_integer",
    "resolve_talib_penetration",
    "sparse_talib_integer_signals",
    "talib_integer_from_outputs",
    "talib_penetration_default",
    "talib_penetration_lookback",
    "undetermined_outputs",
    "validate_talib_adapter_outputs",
    "validate_talib_raw_integer_series",
    "validate_talib_version_pin",
]
