"""Generate a strategy scaffold: the declaration filled in, the decision left to write.

Design: ``docs/fullspec/author_check_and_scaffold_design.md`` section 3.5. One JSON input (the
strategy id, the class name, the series, the timeframes, ``min_history``, the policies, the four
capabilities, the parameters, the twelve ``StrategyProfile`` values, and the display name and
description the registration row needs) becomes four files:

- the strategy module, whose declaration is the input as given, whose ``decision_contract`` is
  always ``DECISION_INTENT``, and whose ``analyze`` reads the inputs and every declared series
  through the ``StrategyBase`` helpers and then returns ``HOLD("scaffold")`` at the one place
  marked for the author;
- the test module, with the declaration test, the registration-file test, and the decision
  test's empty place, keyed by ``series_key_of``;
- the registration SQL, generated by the fact module's ``registration_sql`` and written under
  ``init-scripts/signal-service/<date>/``;
- one ``\\ir`` line appended to ``init-scripts/06-init-signal-registry.sql``.

A scaffold straight out of this tool passes pre-deployment stages 1 to 5 and 7 without a
decision, so what the author fills in is the decision alone. No legacy ``TradingSignal``
scaffold and no policy scaffold are generated. Existing files are never overwritten: the tool
refuses before writing anything.

This module writes files, so it is not part of the fact module.
"""

from __future__ import annotations

import json
import keyword
import subprocess
import sys
import textwrap
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Final

from core_lib.identifiers import PLUGIN_IDENTIFIER_PATTERN, is_plugin_identifier
from core_lib.indicators import DEFAULT_REGISTRY
from core_lib.money_management import MoneyManagementBase, MoneyManagementFactory
from core_lib.patterns import DEFAULT_PATTERN_REGISTRY
from core_lib.series import series_key_of
from core_lib.series_resolution import series_specs_from_descriptors
from core_lib.strategy import FieldSpec, MoneyManagementSupport, ParameterSchema, StrategyProfile

from . import facts
from .author_check import MONEY_MANAGEMENT_OWNED_PARAMETERS
from .discovery import discover_money_management

__all__ = [
    "REPOSITORY_ROOT",
    "ScaffoldResult",
    "ScaffoldSpec",
    "main",
    "render_registration_file",
    "render_strategy_module",
    "render_test_module",
    "scaffold",
]

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[3]
_STRATEGIES: Final = "services/trading-plugins/trading_plugins/strategies"
_TESTS: Final = "services/trading-plugins/tests"
_REGISTRATIONS: Final = "init-scripts/signal-service"
_INIT_SCRIPT: Final = "init-scripts/06-init-signal-registry.sql"
_CAPABILITIES: Final = (
    "supports_external_stop",
    "supports_external_take_profit",
    "supports_signal_exit",
    "supports_pyramiding",
)
_PROFILE_FIELDS: Final = (
    "id",
    "family",
    "bar",
    "expected_win_rate",
    "expected_payoff",
    "tail_shape",
    "holding_horizon",
    "primary_metric",
    "risk_adjusted_pref",
    "profit_structure_to_preserve",
    "envelope_tolerance",
    "envelope_status",
)
_INPUT_KEYS: Final = frozenset(
    {
        "strategy_id",
        "class_name",
        "display_name",
        "description",
        "series",
        "supported_timeframes",
        "min_history",
        "money_management",
        "capabilities",
        "parameters",
        "profile",
        "registration_date",
    }
)
_PARAMETER_KEYS: Final = frozenset({"type", "default", "range", "required"})
StatementBuilder = Callable[[str, str, str], str]


@dataclass(frozen=True)
class ScaffoldSpec:
    """The validated scaffold input."""

    strategy_id: str
    class_name: str
    display_name: str
    description: str
    series: tuple[Mapping[str, Any], ...]
    supported_timeframes: tuple[str, ...]
    min_history: int
    supported_modes: tuple[str, ...]
    default_mode: str
    default_settings: Mapping[str, Mapping[str, Any]]
    capabilities: Mapping[str, bool]
    parameters: Mapping[str, Mapping[str, Any]]
    profile: Mapping[str, Any]
    registration_date: str

    @property
    def module_name(self) -> str:
        return self.strategy_id.replace("-", "_")

    @classmethod
    def from_json(cls, data: Mapping[str, Any]) -> ScaffoldSpec:
        """Validate the input the way the generated declaration will be validated."""
        unknown = sorted(set(data) - _INPUT_KEYS)
        if unknown:
            raise ValueError(f"unknown input keys: {unknown}")
        missing = sorted(_INPUT_KEYS - {"registration_date"} - set(data))
        if missing:
            raise ValueError(f"missing input keys: {missing}")
        strategy_id = _text(data, "strategy_id")
        if not is_plugin_identifier(strategy_id):
            raise ValueError(
                f"strategy_id must be kebab-case ({PLUGIN_IDENTIFIER_PATTERN.pattern}): "
                f"{strategy_id!r}"
            )
        display_name = _docstring_safe(_text(data, "display_name"), "display_name")
        if len(display_name) > 60 or "\n" in display_name:
            raise ValueError("display_name must be one line of at most 60 characters")
        description = _docstring_safe(_text(data, "description"), "description")
        class_name = _text(data, "class_name")
        if (
            not class_name.isidentifier()
            or keyword.iskeyword(class_name)
            or not class_name[0].isupper()
        ):
            raise ValueError(f"class_name must be a capitalized identifier: {class_name!r}")
        series = data["series"]
        if not isinstance(series, list) or not all(
            isinstance(item, dict)
            and isinstance(item.get("name"), str)
            and item["name"]
            and isinstance(item.get("params"), dict)
            and set(item) <= {"name", "params", "timeframe"}
            for item in series
        ):
            raise ValueError("series must be a list of {name, params[, timeframe]} objects")
        timeframes = data["supported_timeframes"]
        if (
            not isinstance(timeframes, list)
            or not timeframes
            or not all(isinstance(item, str) and item for item in timeframes)
        ):
            raise ValueError("supported_timeframes must be a non-empty list of strings")
        min_history = data["min_history"]
        if isinstance(min_history, bool) or not isinstance(min_history, int) or min_history < 1:
            raise ValueError("min_history must be an integer of at least 1")
        money = data["money_management"]
        if not isinstance(money, dict) or set(money) - {"supported", "default", "default_settings"}:
            raise ValueError("money_management must hold supported, default, and default_settings")
        supported = money.get("supported")
        default = money.get("default")
        if (
            not isinstance(supported, list)
            or not supported
            or not all(isinstance(item, str) and is_plugin_identifier(item) for item in supported)
        ):
            raise ValueError("money_management.supported must be a non-empty list of modes")
        if not isinstance(default, str) or default not in supported:
            raise ValueError("money_management.default must be one of the supported modes")
        default_settings = money.get("default_settings", {})
        if not isinstance(default_settings, dict) or not all(
            isinstance(value, dict) for value in default_settings.values()
        ):
            raise ValueError(
                "money_management.default_settings must map a mode to a settings object"
            )
        capabilities = data["capabilities"]
        if (
            not isinstance(capabilities, dict)
            or set(capabilities) != set(_CAPABILITIES)
            or not all(isinstance(value, bool) for value in capabilities.values())
        ):
            raise ValueError(f"capabilities must hold exactly {list(_CAPABILITIES)} as booleans")
        parameters = data["parameters"]
        if not isinstance(parameters, dict):
            raise ValueError("parameters must be an object of name to field")
        for name, spec in parameters.items():
            if not isinstance(name, str) or not name.isidentifier():
                raise ValueError(f"parameter name must be an identifier: {name!r}")
            if name in MONEY_MANAGEMENT_OWNED_PARAMETERS:
                raise ValueError(f"parameter {name!r} belongs to the money-management policy")
            if not isinstance(spec, dict) or "type" not in spec or set(spec) - _PARAMETER_KEYS:
                raise ValueError(
                    f"parameter {name!r} must hold type and optionally default, range, required"
                )
        profile = data["profile"]
        if not isinstance(profile, dict) or set(profile) != set(_PROFILE_FIELDS):
            raise ValueError(f"profile must hold exactly the twelve fields {list(_PROFILE_FIELDS)}")
        date = data.get("registration_date", datetime.now(UTC).strftime("%Y%m%d"))
        if not isinstance(date, str) or len(date) != 8 or not date.isdigit():
            raise ValueError("registration_date must be YYYYMMDD")
        spec = cls(
            strategy_id=strategy_id,
            class_name=class_name,
            display_name=display_name,
            description=description,
            series=tuple(dict(item) for item in series),
            supported_timeframes=tuple(timeframes),
            min_history=min_history,
            supported_modes=tuple(supported),
            default_mode=default,
            default_settings={str(k): dict(v) for k, v in default_settings.items()},
            capabilities={name: bool(capabilities[name]) for name in _CAPABILITIES},
            parameters={str(k): dict(v) for k, v in parameters.items()},
            profile=dict(profile),
            registration_date=date,
        )
        spec.build_profile()
        spec.build_money_management()
        spec.build_parameter_schema()
        spec.validate_against_the_platform()
        return spec

    def validate_against_the_platform(
        self, policies: Mapping[str, type[MoneyManagementBase]] | None = None
    ) -> None:
        """Refuse what pre-deployment stages 2 and 3 would refuse, before any file is written.

        Every timeframe must be well formed, every series must resolve in the registries for
        every supported timeframe, every mode must be deployed with its declared settings
        accepted, and a policy that requires signal exits needs a strategy that emits them.
        """
        for timeframe in self.supported_timeframes:
            try:
                series_key_of("probe", {}, timeframe)
            except ValueError as error:
                raise ValueError(
                    f"supported timeframe {timeframe!r} is malformed: {error}"
                ) from error
        for descriptor in self.series:
            for timeframe in self.supported_timeframes:
                try:
                    series_specs_from_descriptors(
                        [descriptor],
                        DEFAULT_REGISTRY,
                        DEFAULT_PATTERN_REGISTRY,
                        execution_timeframe=timeframe,
                    )
                except (Exception, SystemExit) as error:  # noqa: BLE001 - reported as the reason
                    raise ValueError(
                        f"series {descriptor} does not resolve at {timeframe}: "
                        f"{type(error).__name__}: {error}"
                    ) from error
        deployed = discover_money_management()[0] if policies is None else policies
        for mode in self.supported_modes:
            policy_class = deployed.get(mode)
            if policy_class is None:
                raise ValueError(f"money-management mode {mode!r} is not deployed")
            settings = {"mode": mode, **dict(self.default_settings.get(mode, {}))}
            try:
                policy = MoneyManagementFactory.create(settings, deployed)
            except (Exception, SystemExit) as error:  # noqa: BLE001
                raise ValueError(
                    f"default_settings for {mode!r} are refused: {type(error).__name__}: {error}"
                ) from error
            if policy.requires_signal_exit and not self.capabilities["supports_signal_exit"]:
                raise ValueError(
                    f"mode {mode!r} requires signal exits, but supports_signal_exit is false"
                )

    def build_profile(self) -> StrategyProfile:
        """The profile the generated module declares; building it validates the input."""
        values = dict(self.profile)
        values["expected_win_rate"] = tuple(values["expected_win_rate"])
        values["expected_payoff"] = tuple(values["expected_payoff"])
        return StrategyProfile(**values)

    def build_money_management(self) -> MoneyManagementSupport:
        return MoneyManagementSupport(
            supported=self.supported_modes,
            default=self.default_mode,
            default_settings=self.default_settings,
            **self.capabilities,
        )

    def build_parameter_schema(self) -> ParameterSchema:
        fields: dict[str, FieldSpec] = {}
        for name, spec in self.parameters.items():
            keywords: dict[str, Any] = {"type": spec["type"]}
            if "default" in spec:
                keywords["default"] = spec["default"]
            if "range" in spec:
                keywords["range"] = tuple(spec["range"])
            if "required" in spec:
                keywords["required"] = bool(spec["required"])
            fields[name] = FieldSpec(**keywords)
        return ParameterSchema(fields=fields)


def _text(data: Mapping[str, Any], key: str) -> str:
    value = data.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{key} must be a non-empty string")
    return value


def _docstring_safe(value: str, key: str) -> str:
    """Refuse text that would end or escape the docstring it is written into."""
    if '"""' in value or "\\" in value:
        raise ValueError(f"{key} must not contain a docstring delimiter or a backslash")
    return value


# --- rendering ----------------------------------------------------------------------------


def _literal(value: object) -> str:
    """Render a JSON-like value as Python source in the style ruff format produces."""
    if isinstance(value, bool) or value is None:
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, Mapping):
        inner = ", ".join(f"{_literal(key)}: {_literal(item)}" for key, item in value.items())
        return "{" + inner + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    if isinstance(value, tuple):
        if len(value) == 1:
            return f"({_literal(value[0])},)"
        return "(" + ", ".join(_literal(item) for item in value) + ")"
    raise TypeError(f"cannot render {type(value).__name__} as source")


def _series_label(descriptor: Mapping[str, Any]) -> str:
    params = ", ".join(f"{key}={value}" for key, value in sorted(descriptor["params"].items()))
    label = descriptor["name"] if not params else f"{descriptor['name']}({params})"
    if "timeframe" in descriptor:
        label += f"@{descriptor['timeframe']}"
    return label


def render_strategy_module(spec: ScaffoldSpec) -> str:
    """The strategy module: declaration as given, decision left at the marked place."""
    generated = datetime.now(UTC).strftime("%Y-%m-%d")
    series_lines = "".join(f"                {_literal(item)},\n" for item in spec.series)
    reads = "".join(
        f"            {_literal(_series_label(item))}: self.series("
        f"inputs, {_literal(item['name'])}, {_literal(item['params'])}{_read_timeframe(item)}),\n"
        for item in spec.series
    )
    profile = spec.profile
    capabilities = "".join(
        f"                {name}={_literal(spec.capabilities[name])},\n" for name in _CAPABILITIES
    )
    default_settings = (
        ""
        if not spec.default_settings
        else f"                default_settings={_literal(spec.default_settings)},\n"
    )
    fields = "".join(
        f"                {_literal(name)}: FieldSpec({_field_arguments(item)}),\n"
        for name, item in spec.parameters.items()
    )
    parameter_schema = (
        "        return ParameterSchema(fields={})\n"
        if not spec.parameters
        else "        return ParameterSchema(\n            fields={\n"
        + fields
        + "            }\n        )\n"
    )
    field_spec_import = "    FieldSpec,\n" if spec.parameters else ""
    description = textwrap.fill(spec.description, width=98)
    return f'''"""A scaffold with the declaration filled in and the decision left to write.

{spec.display_name}. {description}

Generated by ``python -m trading_plugins.scaffold`` on {generated}. Everything declared below is
the scaffold input as given; the decision in ``analyze`` is the author's, and nothing else is.
"""

from __future__ import annotations

from typing import ClassVar

from core_lib.strategy import (
{field_spec_import}    MoneyManagementSupport,
    ParameterSchema,
    ResolvedConfig,
    StrategyBase,
    StrategyDecisionContract,
    StrategyMetadata,
    StrategyProfile,
)
from core_lib.types import DecisionAction, DecisionIntent, Position

STRATEGY_ID = {_literal(spec.strategy_id)}


class {spec.class_name}(StrategyBase):
    """{spec.display_name}."""

    STRATEGY_ID: ClassVar[str] = STRATEGY_ID
    VERSION: ClassVar[str] = "1.0.0"

    def __init__(self, config: ResolvedConfig) -> None:
        if config.strategy_id != STRATEGY_ID:
            raise ValueError(f"config is for {{config.strategy_id!r}}, not {{STRATEGY_ID!r}}")
        self.config = config

    @classmethod
    def get_metadata(cls) -> StrategyMetadata:
        return StrategyMetadata(
            # [series 1] the series this strategy declares; the registry owns each warm-up
            required_indicators=[
{series_lines}            ],
            min_history={spec.min_history},
            supported_timeframes={_literal(list(spec.supported_timeframes))},
            profile=StrategyProfile(
                id={_literal(profile["id"])},
                family={_literal(profile["family"])},
                bar={_literal(profile["bar"])},
                expected_win_rate={_literal(tuple(profile["expected_win_rate"]))},
                expected_payoff={_literal(tuple(profile["expected_payoff"]))},
                tail_shape={_literal(profile["tail_shape"])},
                holding_horizon={_literal(profile["holding_horizon"])},
                primary_metric={_literal(profile["primary_metric"])},
                risk_adjusted_pref={_literal(profile["risk_adjusted_pref"])},
                profit_structure_to_preserve={_literal(profile["profit_structure_to_preserve"])},
                envelope_tolerance={_literal(profile["envelope_tolerance"])},
                envelope_status={_literal(profile["envelope_status"])},
            ),
            money_management=MoneyManagementSupport(
                supported={_literal(spec.supported_modes)},
                default={_literal(spec.default_mode)},
{default_settings}{capabilities}            ),
            decision_contract=StrategyDecisionContract.DECISION_INTENT,
        )

    @classmethod
    def get_parameter_schema(cls) -> ParameterSchema:
{parameter_schema}
    def analyze(
        self,
        market_data: dict[str, object],
        current_position: Position | None,
    ) -> DecisionIntent | None:
        inputs = self.read_inputs(market_data)
        # [series 3] the declared series at the deciding bar, read by name and parameters
        series: dict[str, object] = {{
{reads}        }}
        # 여기부터 판단: replace the HOLD below with the document's rule, using ``series``,
        # ``inputs.candles``, ``inputs.market_type`` and ``current_position``.
        del series, current_position
        return self.decide(inputs.candle, DecisionAction.HOLD, "scaffold", adaptee=STRATEGY_ID)
'''


def _read_timeframe(descriptor: Mapping[str, Any]) -> str:
    """The extra argument a series declared on its own timeframe is read with."""
    declared = descriptor.get("timeframe")
    if isinstance(declared, str) and declared != "strategy":
        return f", {_literal(declared)}"
    return ""


def _field_arguments(spec: Mapping[str, Any]) -> str:
    parts = [f"type={_literal(spec['type'])}"]
    if "default" in spec:
        parts.append(f"default={_literal(spec['default'])}")
    if "range" in spec:
        parts.append(f"range={_literal(tuple(spec['range']))}")
    if "required" in spec:
        parts.append(f"required={_literal(bool(spec['required']))}")
    return ", ".join(parts)


def render_test_module(spec: ScaffoldSpec, registration_relative: str) -> str:
    """The test module: the declaration, the registration file, and the decision's empty place."""
    timeframe = spec.supported_timeframes[0]
    indicator_lines = "".join(
        "            series_key_of("
        f"{_literal(item['name'])}, {_literal(item['params'])}, {_timeframe_literal(item)}"
        "): 1.0,\n"
        for item in spec.series
    )
    declared = _literal([dict(item) for item in spec.series])
    return f'''"""Tests for the scaffold: the declaration, the registration file, and the decision.

{spec.class_name} was generated by ``python -m trading_plugins.scaffold``. The first two tests
hold as long as the declaration and the registration file agree; the third is the place for the
document's rule.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime, timedelta
from pathlib import Path

from core_lib.series import series_key_of
from core_lib.strategy import (
    StrategyConfig,
    StrategyDecisionContract,
    catalog_declaration_mismatch,
)
from core_lib.types import Candle, DecisionAction, DecisionIntent
from trading_plugins.strategies.{spec.module_name} import STRATEGY_ID, {spec.class_name}

_REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
_REGISTRATION_FILE = _REPOSITORY_ROOT / {_literal(registration_relative)}
_TIMEFRAME = {_literal(timeframe)}
_START = datetime(2026, 1, 1, tzinfo=UTC)


def _strategy() -> {spec.class_name}:
    resolved = StrategyConfig.resolve(
        {spec.class_name}.get_parameter_schema(), {{"strategy_id": STRATEGY_ID, "params": {{}}}}
    )
    return {spec.class_name}(resolved)


def _candle(index: int, close: float) -> Candle:
    opened = _START + timedelta(hours=index)
    return Candle(
        symbol="BTCUSDT",
        exchange="binance",
        timeframe=_TIMEFRAME,
        open_time=opened,
        close_time=opened + timedelta(hours=1),
        open=close,
        high=close + 1.0,
        low=close - 1.0,
        close=close,
        volume=100.0,
        quote_volume=10_000.0,
        trade_count=100,
    )


def _market_data(candle: Candle) -> dict[str, object]:
    """One deciding bar with a placeholder value for every declared series; fill in real ones."""
    return {{
        "candles": [candle],
        "candle": candle,
        "symbol": candle.symbol,
        "timeframe": _TIMEFRAME,
        "market_type": "futures",
        "indicators": {{
{indicator_lines}        }},
    }}


def test_the_declaration_is_what_the_scaffold_was_given() -> None:
    metadata = {spec.class_name}.get_metadata()
    assert {spec.class_name}.STRATEGY_ID == STRATEGY_ID == {_literal(spec.strategy_id)}
    assert metadata.supported_timeframes == {_literal(list(spec.supported_timeframes))}
    assert metadata.min_history == {spec.min_history}
    assert metadata.money_management.supported == {_literal(spec.supported_modes)}
    assert metadata.money_management.default == {_literal(spec.default_mode)}
    assert metadata.decision_contract is StrategyDecisionContract.DECISION_INTENT
    assert [dict(item) for item in metadata.required_indicators] == {declared}


def test_registration_script_matches_the_code_declaration() -> None:
    sql = _REGISTRATION_FILE.read_text()
    values = re.search(
        r"'(?P<version>\\d+\\.\\d+\\.\\d+)',\\s*"
        r"ARRAY\\[(?P<timeframes>[^\\]]+)\\]::text\\[\\],\\s*"
        r"'(?P<indicators>\\[.*?\\])'::jsonb,\\s*"
        r"(?P<min_history>\\d+),\\s*"
        r"'(?P<defaults>\\{{.*?\\}})'::jsonb,",
        sql,
        re.DOTALL,
    )
    assert values is not None
    row = {{
        "min_history": int(values["min_history"]),
        "supported_timeframes": [
            item.strip().strip("'") for item in values["timeframes"].split(",")
        ],
        "required_indicators_json": json.loads(values["indicators"]),
    }}
    assert values["version"] == {spec.class_name}.VERSION
    assert {_literal(f"'{spec.class_name}'")} in sql
    assert {_literal(f"'trading_plugins.strategies.{spec.module_name}'")} in sql
    assert catalog_declaration_mismatch(row, {spec.class_name}.get_metadata()) is None


def test_the_scaffold_holds_until_the_decision_is_written() -> None:
    # 여기부터 판단 시험: replace this with the document's entry and exit cases per direction.
    decision = _strategy().analyze(_market_data(_candle(0, 100.0)), None)
    assert isinstance(decision, DecisionIntent)
    assert decision.action is DecisionAction.HOLD
    assert decision.reason == "scaffold"
'''


def _timeframe_literal(descriptor: Mapping[str, Any]) -> str:
    declared = descriptor.get("timeframe")
    if isinstance(declared, str) and declared != "strategy":
        return _literal(declared)
    return "_TIMEFRAME"


def render_registration_file(statement: str) -> str:
    """The registration file in the shape the deployed ones have."""
    return f"\\set ON_ERROR_STOP on\n\nBEGIN;\n\n{statement}\n\nCOMMIT;\n"


# --- writing ------------------------------------------------------------------------------


@dataclass(frozen=True)
class ScaffoldResult:
    """Where the four artifacts went."""

    strategy_module: Path
    test_module: Path
    registration_sql: Path
    init_script: Path
    init_script_line: str
    formatted: bool

    def as_json(self) -> dict[str, Any]:
        return {
            "strategy_module": str(self.strategy_module),
            "test_module": str(self.test_module),
            "registration_sql": str(self.registration_sql),
            "init_script": str(self.init_script),
            "init_script_line": self.init_script_line,
            "formatted": self.formatted,
        }


def _default_statement(strategy_id: str, display_name: str, description: str) -> str:
    return facts.registration_sql("strategy", strategy_id, display_name, description, True)


def _next_registration_name(directory: Path, strategy_id: str) -> str:
    existing = sorted(directory.glob("[0-9][0-9]-*.sql")) if directory.exists() else []
    numbers = [int(path.name[:2]) for path in existing]
    return f"{(max(numbers) + 1) if numbers else 1:02d}-register-{strategy_id}.sql"


_SERVICE_CONFIG: Final = Path(__file__).resolve().parents[1] / "pyproject.toml"


def _format(paths: Sequence[Path]) -> bool:
    """Run ruff format over the generated modules so stage 7's format check holds.

    The plugins service's own configuration is named explicitly, so the result does not
    depend on the directory the tool was started from.
    """
    try:
        completed = subprocess.run(  # noqa: S603 - fixed arguments, generated paths
            [
                sys.executable,
                "-m",
                "ruff",
                "format",
                "--config",
                str(_SERVICE_CONFIG),
                *map(str, paths),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return False
    return completed.returncode == 0


def scaffold(
    spec: ScaffoldSpec,
    root: Path = REPOSITORY_ROOT,
    *,
    statement_for: StatementBuilder | None = None,
) -> ScaffoldResult:
    """Write the four artifacts under ``root``; refuse if any of them already exists.

    ``statement_for`` builds the registration statement; the default asks the fact module,
    which discovers the module just written in the deployed package. A test working under
    another root passes its own builder, because discovery looks only at the fixed package.
    """
    strategy_module = root / _STRATEGIES / f"{spec.module_name}.py"
    test_module = root / _TESTS / f"test_{spec.module_name}.py"
    registration_directory = root / _REGISTRATIONS / spec.registration_date
    registration_sql = registration_directory / _next_registration_name(
        registration_directory, spec.strategy_id
    )
    init_script = root / _INIT_SCRIPT
    relative_sql = registration_sql.relative_to(root / "init-scripts").as_posix()
    init_line = f"\\ir {relative_sql}"
    existing = [path for path in (strategy_module, test_module, registration_sql) if path.exists()]
    if existing:
        raise FileExistsError("refusing to overwrite: " + ", ".join(str(path) for path in existing))
    if not init_script.exists():
        raise FileNotFoundError(f"init script is missing: {init_script}")
    if init_line in init_script.read_text().splitlines():
        raise FileExistsError(f"init script already includes {relative_sql}")
    for directory in (strategy_module.parent, test_module.parent, registration_directory):
        directory.mkdir(parents=True, exist_ok=True)

    original_init = init_script.read_text()
    written: list[Path] = []
    try:
        strategy_module.write_text(render_strategy_module(spec))
        written.append(strategy_module)
        builder = _default_statement if statement_for is None else statement_for
        statement = builder(spec.strategy_id, spec.display_name, spec.description)
        registration_sql.write_text(render_registration_file(statement))
        written.append(registration_sql)
        registration_relative = registration_sql.relative_to(root).as_posix()
        test_module.write_text(render_test_module(spec, registration_relative))
        written.append(test_module)
        init_script.write_text(original_init.rstrip("\n") + "\n" + init_line + "\n")
    except BaseException:
        # Leave nothing behind: a half-written scaffold would block the retry through the
        # overwrite guard and sit in the deployed package as a broken module.
        for path in written:
            path.unlink(missing_ok=True)
        init_script.write_text(original_init)
        raise
    formatted = _format((strategy_module, test_module))
    return ScaffoldResult(
        strategy_module, test_module, registration_sql, init_script, init_line, formatted
    )


_USAGE: Final = "usage: python -m trading_plugins.scaffold <input.json>"


def main(argv: Sequence[str] | None = None) -> int:
    """Generate the scaffold from one JSON file; print where the files went, or the error."""
    arguments = list(sys.argv[1:] if argv is None else argv)
    if len(arguments) != 1:
        print(json.dumps({"error": _USAGE}))
        return 1
    try:
        loaded = json.loads(Path(arguments[0]).read_text())
        if not isinstance(loaded, dict):
            raise ValueError("input must be a JSON object")
        result = scaffold(ScaffoldSpec.from_json(loaded))
    except (Exception, SystemExit) as error:  # noqa: BLE001 - the boundary reports, never raises
        print(json.dumps({"error": f"{type(error).__name__}: {error}"}))
        return 1
    print(json.dumps(result.as_json(), sort_keys=True))
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised through main() in tests
    sys.exit(main())
