"""Registration list owned by the momentum category."""

from functools import partial

from core_lib.indicators import momentum
from core_lib.indicators.registry import IndicatorSpec

RSI_MIN_HISTORY = 15

SPECS: tuple[IndicatorSpec, ...] = (
    IndicatorSpec(
        name="RSI",
        params={"period": 14},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.1 + §0.5 (Wilder RMA)",
        min_history=15,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.rsi, period=14),
        _state_factory=partial(momentum.RSIState, period=14),
    ),
    IndicatorSpec(
        name="Stochastic",
        params={"period": 14, "smooth_period": 3},
        version="1.0.0",
        pinned_impl=(
            "technical_indicators_calc_spec.md §2.2 "
            "(fast %K/%D; flat range keeps previous, initially 50)"
        ),
        min_history=16,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.stochastic, period=14, smooth_period=3),
        _state_factory=partial(momentum.StochasticState, period=14, smooth_period=3),
    ),
    IndicatorSpec(
        name="MACD",
        params={"fast_period": 12, "slow_period": 26, "signal_period": 9},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.4 (12/26/9, EMA of MACD)",
        min_history=34,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.macd,
            fast_period=12,
            slow_period=26,
            signal_period=9,
        ),
        _state_factory=partial(
            momentum.MACDState,
            fast_period=12,
            slow_period=26,
            signal_period=9,
        ),
    ),
    IndicatorSpec(
        name="TSI",
        params={"long_period": 25, "short_period": 13},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.7 (double-smoothed momentum)",
        min_history=38,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.tsi, long_period=25, short_period=13),
        _state_factory=partial(momentum.TSIState, long_period=25, short_period=13),
    ),
    IndicatorSpec(
        name="CCI",
        params={"period": 20},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.10 (0.015 * mean deviation)",
        min_history=20,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.cci, period=20),
        _state_factory=partial(momentum.CCIState, period=20),
    ),
    IndicatorSpec(
        name="Awesome Oscillator",
        params={"fast_period": 5, "slow_period": 34},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.12 (SMA of HL2, 5 and 34)",
        min_history=34,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.awesome_oscillator, fast_period=5, slow_period=34),
        _state_factory=partial(
            momentum.AwesomeOscillatorState,
            fast_period=5,
            slow_period=34,
        ),
    ),
    IndicatorSpec(
        name="PPO",
        params={"fast_period": 12, "slow_period": 26, "signal_period": 9},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.5 (MACD scaled by the slow EMA)",
        min_history=34,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.ppo,
            fast_period=12,
            slow_period=26,
            signal_period=9,
        ),
        _state_factory=partial(
            momentum.PPOState,
            fast_period=12,
            slow_period=26,
            signal_period=9,
        ),
    ),
    IndicatorSpec(
        name="SMI",
        params={
            "period": 13,
            "long_period": 25,
            "short_period": 13,
            "signal_period": 3,
        },
        version="1.0.0",
        pinned_impl=(
            "technical_indicators_calc_spec.md §2.27 "
            "(Blau 13/25/13 with a 3-period signal; the section asks the set to be stated)"
        ),
        min_history=51,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.smi,
            period=13,
            long_period=25,
            short_period=13,
            signal_period=3,
        ),
        _state_factory=partial(
            momentum.SMIState,
            period=13,
            long_period=25,
            short_period=13,
            signal_period=3,
        ),
    ),
    IndicatorSpec(
        name="Accelerator Oscillator",
        params={"fast_period": 5, "slow_period": 34, "smooth_period": 5},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.13 (AO - SMA(AO, 5))",
        min_history=38,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.accelerator_oscillator,
            fast_period=5,
            slow_period=34,
            smooth_period=5,
        ),
        _state_factory=partial(
            momentum.AcceleratorOscillatorState,
            fast_period=5,
            slow_period=34,
            smooth_period=5,
        ),
    ),
    IndicatorSpec(
        name="Stochastic RSI",
        params={
            "rsi_period": 14,
            "stochastic_period": 14,
            "smooth_k": 3,
            "smooth_d": 3,
        },
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.3 (stochastic of RSI, 3/3 smoothing)",
        min_history=RSI_MIN_HISTORY + 14 + 3 + 3 - 3,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.stochastic_rsi,
            rsi_period=14,
            stochastic_period=14,
            smooth_k=3,
            smooth_d=3,
        ),
        _state_factory=partial(
            momentum.StochasticRSIState,
            rsi_period=14,
            stochastic_period=14,
            smooth_k=3,
            smooth_d=3,
        ),
    ),
    IndicatorSpec(
        name="TRIX",
        params={"period": 15},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.6 (triple EMA, TA-Lib 100x scale)",
        min_history=44,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.trix, period=15),
        _state_factory=partial(momentum.TRIXState, period=15),
    ),
    IndicatorSpec(
        name="CMO",
        params={"period": 14},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.8 (unsmoothed sums)",
        min_history=15,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.cmo, period=14),
        _state_factory=partial(momentum.CMOState, period=14),
    ),
    IndicatorSpec(
        name="Williams %R",
        params={"period": 14},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.9 (stochastic read from the high)",
        min_history=14,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.williams_r, period=14),
        _state_factory=partial(momentum.WilliamsRState, period=14),
    ),
    IndicatorSpec(
        name="Ultimate Oscillator",
        params={"short_period": 7, "medium_period": 14, "long_period": 28},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.11 (7/14/28 weighted 4:2:1)",
        min_history=29,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.ultimate_oscillator,
            short_period=7,
            medium_period=14,
            long_period=28,
        ),
        _state_factory=partial(
            momentum.UltimateOscillatorState,
            short_period=7,
            medium_period=14,
            long_period=28,
        ),
    ),
    IndicatorSpec(
        name="Fisher Transform",
        params={"period": 9},
        version="1.0.0",
        pinned_impl=(
            "technical_indicators_calc_spec.md §2.14 "
            "(n=9 of the 9-10 the section allows; clamped at 0.999)"
        ),
        min_history=10,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(momentum.fisher_transform, period=9),
        _state_factory=partial(momentum.FisherTransformState, period=9),
    ),
    IndicatorSpec(
        name="KST",
        params={},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.24 (four weighted rate-of-change legs)",
        min_history=53,
        category="momentum",
        required_inputs=(),
        _vectorized=momentum.kst,
        _state_factory=momentum.KSTState,
    ),
    IndicatorSpec(
        name="Coppock Curve",
        params={"long_period": 14, "short_period": 11, "smooth_period": 10},
        version="1.0.0",
        pinned_impl="technical_indicators_calc_spec.md §2.25 (WMA of two rates of change)",
        min_history=24,
        category="momentum",
        required_inputs=(),
        _vectorized=partial(
            momentum.coppock_curve,
            long_period=14,
            short_period=11,
            smooth_period=10,
        ),
        _state_factory=partial(
            momentum.CoppockCurveState,
            long_period=14,
            short_period=11,
            smooth_period=10,
        ),
    ),
)
