/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Summary */
        get: operations["get_run_summary_api_v1_runs__run_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogHealth */
        CatalogHealth: {
            /**
             * Status
             * @constant
             */
            status: "connected";
            /** Database */
            database: string;
            /** Read Only */
            read_only: boolean;
            /** Run Count */
            run_count: number;
            /** Schema Version */
            schema_version: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            details?: components["schemas"]["JsonValue"] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            catalog: components["schemas"]["CatalogHealth"];
            /** Core Lib Version */
            core_lib_version: string;
            /** Web Api Version */
            web_api_version: string;
        };
        JsonValue: unknown;
        /**
         * Page
         * @description Offset page metadata.
         */
        Page: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * RunHeader
         * @description Reproducibility header mirroring every backtest_run column.
         */
        RunHeader: {
            /** Run Id */
            run_id: string;
            /** Run Seq */
            run_seq: number;
            /** Run Name */
            run_name: string;
            /** Status */
            status: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /** Strategy Version */
            strategy_version: string;
            params_json: components["schemas"]["JsonValue"];
            /** Params Schema Version */
            params_schema_version: string;
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange: string;
            /** Timeframe */
            timeframe: string;
            /** Market Type */
            market_type: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /** Warmup Start */
            warmup_start: string | null;
            /** Warmup Candles */
            warmup_candles: number;
            /** Data Source */
            data_source: string;
            /** Indicator Mode */
            indicator_mode: string;
            /** Trigger Feed */
            trigger_feed: string;
            /** Fill Timing */
            fill_timing: string;
            /**
             * Initial Capital
             * Format: decimal
             * @description Exact PostgreSQL NUMERIC value serialized without floating-point conversion.
             */
            initial_capital: string;
            /** Sizing Method */
            sizing_method: string;
            /** Risk Per Trade */
            risk_per_trade: string | null;
            /** Position Size Pct */
            position_size_pct: string | null;
            /** Framework Compliant */
            framework_compliant: boolean;
            cost_values_json: components["schemas"]["JsonValue"];
            /** Seed */
            seed: number;
            /** Engine Version */
            engine_version: string;
            /** Core Lib Version */
            core_lib_version: string;
            /** Config Hash */
            config_hash: string;
            /** Profile Ref */
            profile_ref: string | null;
            strategy_profile_json: components["schemas"]["JsonValue"] | null;
            /** Envelope Status Declared */
            envelope_status_declared: string | null;
            /** Sweep Id */
            sweep_id: string | null;
            /** Fold Label */
            fold_label: string | null;
            /** Evidence Path */
            evidence_path: string | null;
            /** Evidence Hash */
            evidence_hash: string | null;
            /** Evidence Retained */
            evidence_retained: boolean;
            /** Evidence Expires At */
            evidence_expires_at: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            resolved_indicators_json: components["schemas"]["JsonValue"];
            /** Source Data Hash */
            source_data_hash: string | null;
        };
        /**
         * RunListItem
         * @description Thin catalog row with an optional stored summary.
         */
        RunListItem: {
            /** Run Id */
            run_id: string;
            /** Run Name */
            run_name: string;
            /** Status */
            status: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange: string;
            /** Timeframe */
            timeframe: string;
            /** Market Type */
            market_type: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sweep Id */
            sweep_id: string | null;
            /** Config Hash */
            config_hash: string;
            /** Trade Count */
            trade_count: number | null;
            /** Pf */
            pf: number | null;
            /** Sortino */
            sortino: number | null;
            /** Calmar Or Mar */
            calmar_or_mar: number | null;
            /** Sqn */
            sqn: number | null;
            /** Mdd */
            mdd: number | null;
            /** Ror */
            ror: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Net Pnl Total */
            net_pnl_total: string | null;
            /** Gate Verdict */
            gate_verdict: string | null;
            /** Decision Route */
            decision_route: string | null;
            /** Integrity Status */
            integrity_status: string | null;
            /** Data Coverage Ratio */
            data_coverage_ratio: number | null;
            /** Summary Present */
            summary_present: boolean;
        };
        /**
         * RunListResponse
         * @description Catalog collection envelope.
         */
        RunListResponse: {
            /** Data */
            data: components["schemas"]["RunListItem"][];
            page: components["schemas"]["Page"];
        };
        /**
         * RunSummary
         * @description Stored backtest_summary row; values are never recomputed here.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Trade Count */
            trade_count: number;
            /** Win Count */
            win_count: number;
            /** Loss Count */
            loss_count: number;
            /** R Excluded Count */
            r_excluded_count: number;
            /** Pf */
            pf: number | null;
            /** Sortino */
            sortino: number | null;
            /** Calmar Or Mar */
            calmar_or_mar: number | null;
            /** Calmar Basis */
            calmar_basis: string | null;
            /** Sqn */
            sqn: number | null;
            /** Mdd */
            mdd: number | null;
            /** Ror */
            ror: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Payoff */
            payoff: number | null;
            /** Expectancy R */
            expectancy_r: number | null;
            /** Ulcer */
            ulcer: number | null;
            /** Kelly */
            kelly: number | null;
            /** Annualization */
            annualization: string;
            /**
             * Initial Capital
             * Format: decimal
             * @description Exact PostgreSQL NUMERIC value serialized without floating-point conversion.
             */
            initial_capital: string;
            /** Final Equity */
            final_equity: string | null;
            /** Net Pnl Total */
            net_pnl_total: string | null;
            /** Gross Pnl Total */
            gross_pnl_total: string | null;
            /** Total Fee */
            total_fee: string | null;
            /** Total Slippage */
            total_slippage: string | null;
            /** Total Funding */
            total_funding: string | null;
            /** Total Liquidation Penalty */
            total_liquidation_penalty: string | null;
            /** Integrity Passed */
            integrity_passed: boolean;
            /** Integrity Status */
            integrity_status: string;
            integrity_failed_json: components["schemas"]["JsonValue"] | null;
            /** Gate Passed */
            gate_passed: boolean | null;
            /** Gate Stage */
            gate_stage: string | null;
            /** Gate Verdict */
            gate_verdict: string | null;
            gate_failed_json: components["schemas"]["JsonValue"] | null;
            /** Envelope Result */
            envelope_result: string | null;
            envelope_deviated_json: components["schemas"]["JsonValue"] | null;
            /** Decision Route */
            decision_route: string | null;
            /** Decision Rationale */
            decision_rationale: string | null;
            /** Oos Degradation */
            oos_degradation: number | null;
            /** Psr */
            psr: number | null;
            harness_json: components["schemas"]["JsonValue"] | null;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Expected Candle Count */
            expected_candle_count: number;
            /** Observed Candle Count */
            observed_candle_count: number;
            /** Source Absent Gap Count */
            source_absent_gap_count: number;
            /** Partial Bucket Count */
            partial_bucket_count: number;
            /** Data Coverage Ratio */
            data_coverage_ratio: number;
            /** Max Consecutive Gap Bars */
            max_consecutive_gap_bars: number;
            /** Max Consecutive Gap Seconds */
            max_consecutive_gap_seconds: number;
            /** Data Coverage Passed */
            data_coverage_passed: boolean;
            /** Unobservable Funding Boundary Count */
            unobservable_funding_boundary_count: number;
            /** Data Gap Exit Count */
            data_gap_exit_count: number;
        };
        /**
         * RunSummaryResponse
         * @description 0..1 stored summary with a status-derived absence explanation.
         */
        RunSummaryResponse: {
            /** Run Id */
            run_id: string;
            /** Run Status */
            run_status: string;
            /**
             * Summary Status
             * @enum {string}
             */
            summary_status: "available" | "pending" | "failed" | "orphaned" | "missing";
            summary: components["schemas"]["RunSummary"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                symbol?: string | null;
                timeframe?: string | null;
                exchange?: string | null;
                market_type?: string | null;
                status?: string | null;
                decision_route?: string | null;
                gate_passed?: boolean | null;
                sweep_id?: string | null;
                config_hash?: string | null;
                created_at_from?: string | null;
                created_at_to?: string | null;
                period_start_from?: string | null;
                period_start_to?: string | null;
                period_end_from?: string | null;
                period_end_to?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHeader"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_summary_api_v1_runs__run_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
